// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoolbetIntegration.API.Data;

#nullable disable

namespace PoolbetIntegration.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231219200951_Add_transaction")]
    partial class Add_transaction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PoolbetIntegration.API.Features.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BetId")
                        .IsRequired()
                        .HasColumnType("string");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("TransactionId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("PoolbetIntegration.API.Features.UserAdmins.UserAdmin", b =>
                {
                    b.Property<int>("UserAdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAdminId"));

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Credit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Name");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Username");

                    b.HasKey("UserAdminId");

                    b.ToTable("UserAdmin", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
